Package.swift, Sources/Slipstream/Documentation.docc/Architecture/HowSlipstreamWorks.md, Sources/Slipstream/Documentation.docc/DataAndStorage/Environment.md, Sources/Slipstream/Documentation.docc/DataAndStorage/EnvironmentValues.md, Sources/Slipstream/Documentation.docc/DataAndStorage/EnvironmentValuesSection.md, Sources/Slipstream/Documentation.docc/Slipstream.md, Sources/Slipstream/Documentation.docc/Views/Fundamentals/Fundamentals.md, Sources/Slipstream/Documentation.docc/Views/Fundamentals/View.md, Sources/Slipstream/Rendering/Render.swift, Sources/Slipstream/Views/Fundamentals/DataAndStorage/Environment.swift, Sources/Slipstream/Views/Fundamentals/DataAndStorage/EnvironmentKey.swift, Sources/Slipstream/Views/Fundamentals/DataAndStorage/EnvironmentValues.swift, Sources/Slipstream/Views/Fundamentals/View+environment.swift, Sources/Slipstream/Views/Fundamentals/View+modifier.swift, Sources/Slipstream/Views/Fundamentals/View.swift, Sources/Slipstream/Views/Fundamentals/ViewBuilder.swift, Sources/Slipstream/Views/Fundamentals/ViewModifier.swift, Sources/Slipstream/Views/TextInputAndOutput/Text.swift, Sources/TypeIntrospection/Properties.swift, Sources/TypeIntrospection/PropertyIntrospection/PropertyIntrospection-Access.swift, Sources/TypeIntrospection/PropertyIntrospection/PropertyIntrospection.swift, Sources/TypeIntrospection/TypeIntrospection.swift, Tests/SlipstreamTests/EnvironmentTests.swift, Tests/TypeIntrospectionTests/TypeIntrospectionTests.swift
This change introduces the ability to define, read, and write environment properties within any Slipstream View type.
=> Add @Environment support + documentation.

Sources/Slipstream/Documentation.docc/Views/Fundamentals/Fundamentals.md, Sources/Slipstream/Views/Fundamentals/EmptyView.swift, Sources/Slipstream/Views/Fundamentals/View.swift, Sources/Slipstream/Views/Fundamentals/ViewBuilder/ArrayView.swift, Sources/Slipstream/Views/Fundamentals/ViewBuilder/ConditionalView.swift, Sources/Slipstream/Views/Fundamentals/ViewBuilder/TupleView.swift, Sources/Slipstream/Views/Fundamentals/ViewBuilder/ViewBuilder.swift, Tests/SlipstreamTests/ViewBuilderTests.swift
Closes https://github.com/jverkoey/slipstream/issues/22
=> Add support for if statements.

Sources/Slipstream/Views/W3C/Elements/HTML.swift
Add an example and link to related APIs.
=> Tune HTML's documentation.

Sources/Slipstream/Documentation.docc/Views/W3C/HTML.md, Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md, Sources/Slipstream/Views/W3C/Elements/Body.swift, Tests/SlipstreamTests/Sites/CatalogSiteTests.swift, Tests/SlipstreamTests/Views/W3C/BodyTests.swift
=> Add body element implementation.

Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md, Sources/Slipstream/Views/W3C/Elements/DocumentMetadata/Viewport.swift, Tests/SlipstreamTests/Sites/CatalogSiteTests.swift, Tests/SlipstreamTests/Views/W3C/ViewportTests.swift
=> Add meta element viewport implementation.

Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md, Sources/Slipstream/Views/W3C/Elements/GroupingContent/Div.swift, Tests/SlipstreamTests/Sites/CatalogSiteTests.swift, Tests/SlipstreamTests/Views/W3C/DivTests.swift
=> Add Div implementation.

Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md, Sources/Slipstream/W3C/Elements/Sections/H1.swift, Sources/Slipstream/W3C/Elements/Sections/H2.swift, Sources/Slipstream/W3C/Elements/Sections/H3.swift, Sources/Slipstream/W3C/Elements/Sections/H4.swift, Sources/Slipstream/W3C/Elements/Sections/H5.swift, Sources/Slipstream/W3C/Elements/Sections/H6.swift, Tests/SlipstreamTests/Sites/CatalogSiteTests.swift, Tests/SlipstreamTests/Views/W3C/HeadingTests.swift
=> Add h1-h6 implementations.

Sources/Slipstream/Documentation.docc/Views/Fundamentals/Fundamentals.md, Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSViews.md, Sources/Slipstream/TailwindCSS/Typography/View+textAlignment.swift, Tests/SlipstreamTests/Sites/CatalogSiteTests.swift, Tests/SlipstreamTests/Views/TailwindCSS/TextAlignmentTests.swift
=> Add textAlignment modifier.

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Margin.md, Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSClasses.md, Sources/Slipstream/TailwindCSS/Edge.swift, Sources/Slipstream/TailwindCSS/Spacing/View+margin.swift, Sources/Slipstream/TailwindCSS/Spacing/View+padding.swift, Sources/Slipstream/TailwindCSS/Typography/View+fontSize.swift, Sources/Slipstream/TailwindCSS/Typography/View+fontSmoothing.swift, Sources/Slipstream/TailwindCSS/Typography/View+fontWeight.swift, Sources/Slipstream/TailwindCSS/Typography/View+textAlignment.swift, Tests/SlipstreamTests/Sites/CatalogSiteTests.swift, Tests/SlipstreamTests/TailwindCSS/MarginTests.swift
=> Add margin modifier.

Sources/Slipstream/Documentation.docc/Views/W3C/Scripting/Script.md, Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md, Sources/Slipstream/W3C/Elements/DocumentMetadata/Meta.swift, Sources/Slipstream/W3C/Elements/Scripting/Script.swift, Tests/SlipstreamTests/Sites/CatalogSiteTests.swift, Tests/SlipstreamTests/W3C/ScriptTests.swift
Part of https://github.com/jverkoey/slipstream/issues/25
=> Implement Script view.

Sources/Slipstream/Documentation.docc/Slipstream.md, Sources/Slipstream/Documentation.docc/TailwindCSS/Borders/Borders-CornerRadius.md, Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md, Sources/Slipstream/TailwindCSS/Borders/View+cornerRadius.swift, Tests/SlipstreamTests/TailwindCSS/Borders/CornerRadiusTests.swift
=> Add cornerRadius modifier.

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md, Sources/Slipstream/W3C/Elements/GroupingContent/Divider.swift, Sources/Slipstream/W3C/Elements/Scripting/Script.swift, Tests/SlipstreamTests/Sites/CatalogSiteTests.swift, Tests/SlipstreamTests/W3C/DividerTests.swift
=> Add Divider view.

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md, Sources/Slipstream/W3C/Elements/GroupingContent/Blockquote.swift, Tests/SlipstreamTests/W3C/BlockquoteTests.swift
=> Add Blockquote element.

Sources/Slipstream/TailwindCSS/Condition.swift, Tests/SlipstreamTests/TailwindCSS/Spacing/MarginTests.swift
=> Don't bother emitting sm: modifier.

Sources/Slipstream/TailwindCSS/Sizing/FrameTypes/FrameHeightValue.swift
Accidentally used `w` instead of `h` due to copy-pasting code.
=> [breaking] Fix typo in frame height viewport constants.

Sources/Slipstream/W3C/Elements/DocumentMetadata/Viewport.swift, Tests/SlipstreamTests/W3C/ViewportTests.swift
This appears to be a non-standard feature but it's a quick way to make web pages fill the whole screen width in landscape on iPhone with notches/dynamic islands.
=> [feature] Add viewport-fit to Viewport.

.github/workflows/package-test.yml, Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md, Sources/Slipstream/Documentation.docc/W3C/W3CViews.md, Sources/Slipstream/W3C/Elements/TabularData/Table.swift, Sources/Slipstream/W3C/Elements/TabularData/TableBody.swift, Sources/Slipstream/W3C/Elements/TabularData/TableCell.swift, Sources/Slipstream/W3C/Elements/TabularData/TableHeader.swift, Sources/Slipstream/W3C/Elements/TabularData/TableHeaderCell.swift, Sources/Slipstream/W3C/Elements/TabularData/TableRow.swift, Tests/SlipstreamTests/W3C/TabularData/TableBodyTests.swift, Tests/SlipstreamTests/W3C/TabularData/TableCellTests.swift, Tests/SlipstreamTests/W3C/TabularData/TableHeaderCellTests.swift, Tests/SlipstreamTests/W3C/TabularData/TableHeaderTests.swift, Tests/SlipstreamTests/W3C/TabularData/TableRowTests.swift, Tests/SlipstreamTests/W3C/TabularData/TableTests.swift
=> Add basic Table elements.

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md, Sources/Slipstream/Documentation.docc/W3C/W3CViews.md, Sources/Slipstream/Fundamentals/ViewBuilder/ArrayView.swift, Sources/Slipstream/Fundamentals/ViewBuilder/ConditionalView.swift, Sources/Slipstream/Fundamentals/ViewBuilder/TupleView.swift, Sources/Slipstream/W3C/Elements/Scripting/Canvas.swift, Tests/SlipstreamTests/W3C/CanvasTests.swift
=> Add Canvas view.

Sources/Slipstream/TailwindCSS/Typography/View+fontSize.swift, Tests/SlipstreamTests/TailwindCSS/Typography/FontSizeTests.swift
Tried bringing support for arbitrary pixel values for `fontSize`.
Maybe there is a better way to bring a more generic support for arbitrary values, but keeping it simple for now since I'm super new to this codebase.
fixes #60
#first-contribution (maybe? 🙂)
=> Adds arbitrary pixel values support for font sizes. (#60)

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md, Sources/Slipstream/Documentation.docc/W3C/W3CViews.md, Sources/Slipstream/W3C/Elements/Sections/Section.swift, Tests/SlipstreamTests/W3C/SectionTests.swift
=> Add Section.

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md, Sources/Slipstream/Documentation.docc/Guides/SlipstreamforSwiftUIDevelopers.md, Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md, Sources/Slipstream/TailwindCSS/Filters/View+colorInvert.swift, Tests/SlipstreamTests/TailwindCSS/Filters/ColorInvertTests.swift
=> Add colorInvert modifier.

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md, Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md, Sources/Slipstream/TailwindCSS/Effects/View+opacity.swift, Tests/SlipstreamTests/TailwindCSS/Effects/OpacityTests.swift
=> Add opacity modifier.

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md, Sources/Slipstream/Documentation.docc/TailwindCSS/Layout/Layout-Overflow.md, Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md, Sources/Slipstream/TailwindCSS/Layout/View+overflow.swift, Tests/SlipstreamTests/TailwindCSS/Layout/OverflowTests.swift
=> Add clipsToBounds and overflow modifiers.

Sources/Slipstream/Fundamentals/ViewBuilder/ForEachView.swift, Tests/SlipstreamTests/ForEachTests.swift
This PR introduces a new ForEachView component to Slipstream, enabling iteration over collections to dynamically render repeated content. It is inspired by SwiftUI’s ForEach, but tailored for Slipstream’s ViewBuilder system. For example:
```swift
ForEach(articles, id: \.id) { article in
ArticleView(article: article)
}
```
The implementation provides type safety through generics and RandomAccessCollection constraints, and streamlines the rendering of list-based UI components by supporting both Identifiable elements and explicit id key paths.
Unit tests cover:
•	Iteration with Identifiable collections
•	Iteration with custom id key paths
•	Rendering links and styled elements via modifiers
•	Handling empty collections with explicit fallback content
=> Add ForEach view for iterating over collections
