ClutchEngineering/slipstream

Sources/Slipstream/Documentation.docc/Views/Architecture/HowSlipstreamWorks.md
Sources/Slipstream/Documentation.docc/Views/Catalog.md

Was causing duplication of navigation.

Remove the Catalog.

---

Sources/Slipstream/Documentation.docc/Views/Fundamentals/ViewBuilder.md
Sources/Slipstream/Views/Fundamentals/ViewBuilder/ArrayView.swift
Sources/Slipstream/Views/Fundamentals/ViewBuilder/ViewBuilder.swift
Tests/SlipstreamTests/ViewBuilderTests.swift

Closes https://github.com/jverkoey/slipstream/issues/20

Add support for for loops in View.

---

Sources/Slipstream/Documentation.docc/Slipstream.md
Sources/Slipstream/Documentation.docc/Views/W3C/HTML.md
Sources/Slipstream/Documentation.docc/Views/W3C/W3C.md
Sources/Slipstream/Views/W3C/HTML.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/Views/W3C/HTMLTests.swift

Part of https://github.com/jverkoey/slipstream/issues/25

Add support for the HTML view.

---

Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md
Sources/Slipstream/Views/W3C/Attributes/View+language.swift
Sources/Slipstream/Views/W3C/Elements/HTML.swift
Sources/Slipstream/Views/W3C/Elements/Head.swift
Sources/Slipstream/Views/W3C/Elements/W3CElement.swift
Tests/SlipstreamTests/Views/W3C/HeadTests.swift

Add head element implementation.

---

Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md
Sources/Slipstream/Views/W3C/Elements/DocumentMetadata/Title.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/Views/W3C/TitleTests.swift

Add title element implementation.

---

Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md
Sources/Slipstream/Views/W3C/Elements/DocumentMetadata/Meta.swift
Sources/Slipstream/Views/W3C/Elements/DocumentMetadata/Stylesheet.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/Views/W3C/StylesheetTests.swift

Add Stylesheet implementation.

---

Sources/Slipstream/Documentation.docc/Views/W3C/W3CAttributes.md
Sources/Slipstream/Views/Fundamentals/AttributeModifier.swift
Sources/Slipstream/Views/Fundamentals/ClassModifier.swift
Sources/Slipstream/Views/W3C/Attributes/View+class.swift
Sources/Slipstream/Views/W3C/Attributes/View+id.swift
Tests/SlipstreamTests/Attributes/ClassTests.swift
Tests/SlipstreamTests/Attributes/IDTests.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift

Part of https://github.com/jverkoey/slipstream/issues/27.

Add class modifier.

---

Sources/Slipstream/Documentation.docc/Slipstream.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSViews.md
Sources/Slipstream/TailwindCSS/Layout/Container.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/Views/TailwindCSS/ContainerTests.swift

Add Tailwind Container implementation.

---

Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/TextLevelSemantics/LineBreak.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/Views/W3C/LinebreakTests.swift

Add <br> implementation as Linebreakl.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSClasses.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/fontSize.md
Sources/Slipstream/TailwindCSS/Typography/View+fontSize.swift
Sources/Slipstream/TailwindCSS/Typography/View+textAlignment.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/FontSizeTests.swift

Add fontSize modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FontSize.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FontWeight.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSClasses.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TextAlignment.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/fontSize.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/textAlignment.md
Sources/Slipstream/TailwindCSS/Typography/View+fontWeight.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/FontSizeTests.swift
Tests/SlipstreamTests/TailwindCSS/FontWeightTests.swift

Add fontWeight and bold modifiers.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FontSmoothing.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSClasses.md
Sources/Slipstream/TailwindCSS/Typography/View+fontSmoothing.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/FontSmoothingTests.swift

Add fontSmoothing and antialiased modifiers.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Padding.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSClasses.md
Sources/Slipstream/TailwindCSS/Edge.swift
Sources/Slipstream/TailwindCSS/Spacing/View+padding.swift
Sources/Slipstream/TailwindCSS/Typography/View+fontSize.swift
Sources/Slipstream/TailwindCSS/Typography/View+fontWeight.swift
Sources/Slipstream/TailwindCSS/Typography/View+textAlignment.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/PaddingTests.swift
Tests/SlipstreamTests/TailwindCSS/TextAlignmentTests.swift

Add padding modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSClasses.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TextColor.md
Sources/Slipstream/TailwindCSS/Color.swift
Sources/Slipstream/TailwindCSS/ColorPalette.swift
Sources/Slipstream/TailwindCSS/Typography/View+fontSize.swift
Sources/Slipstream/TailwindCSS/Typography/View+fontSmoothing.swift
Sources/Slipstream/TailwindCSS/Typography/View+fontWeight.swift
Sources/Slipstream/TailwindCSS/Typography/View+textAlignment.swift
Sources/Slipstream/TailwindCSS/Typography/View+textColor.swift
Sources/Slipstream/W3C/Elements/GroupingContent/Div.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/MarginTests.swift
Tests/SlipstreamTests/TailwindCSS/TextColorTests.swift

Add textColor modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Display.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FontSize.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FontSmoothing.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FontWeight.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Margin.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Padding.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSClasses.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TextAlignment.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TextColor.md
Sources/Slipstream/TailwindCSS/Layout/View+display.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/DisplayTests.swift

Add display modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSSClasses.md
Sources/Slipstream/TailwindCSS/Layout/HStack.swift
Sources/Slipstream/TailwindCSS/Layout/VStack.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/Layout/HStackTests.swift
Tests/SlipstreamTests/TailwindCSS/Layout/VStackTests.swift

These views are abstractions around flexbox, specifically flex-row and flex-col, respectively.

Add HStack/VStack.

---

Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/TextLevelSemantics/Link.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/W3C/LinkTests.swift

Add Link view.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Spacing/Spacing-Margin.md
Sources/Slipstream/TailwindCSS/Edge.swift
Sources/Slipstream/TailwindCSS/Layout/HStack.swift
Sources/Slipstream/TailwindCSS/Layout/VStack.swift
Sources/Slipstream/TailwindCSS/Spacing/View+margin.swift
Sources/Slipstream/TailwindCSS/Spacing/View+padding.swift
Sources/Slipstream/TailwindCSS/Typography/View+fontSize.swift
Sources/Slipstream/W3C/Elements/TextLevelSemantics/Link.swift
Tests/SlipstreamTests/TailwindCSS/Spacing/MarginTests.swift
Tests/SlipstreamTests/TailwindCSS/Spacing/PaddingTests.swift

Also fixed some broken/missing documentation.

Add default margin/padding convenience methods.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Borders/Borders-Border.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Typography/Typography-FontSize.md
Sources/Slipstream/TailwindCSS/Borders/View+border.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/Borders/BorderTests.swift

Add border modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FlexboxAndGrid/FlexboxAndGrid-FlexDirection.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FlexboxAndGrid/FlexboxAndGrid-FlexGap.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/TailwindCSS/Axis.swift
Sources/Slipstream/TailwindCSS/FlexboxAndGrid/View+flexDirection.swift
Sources/Slipstream/TailwindCSS/FlexboxAndGrid/View+flexGap.swift
Sources/Slipstream/TailwindCSS/Layout/HStack.swift
Sources/Slipstream/TailwindCSS/Layout/VStack.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/FlexboxAndGrid/FlexDirectionTests.swift
Tests/SlipstreamTests/TailwindCSS/FlexboxAndGrid/FlexGapTests.swift

Add flexGap modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FlexboxAndGrid/FlexboxAndGrid-FlexDirection.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FlexboxAndGrid/FlexboxAndGrid-FlexGap.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Layout/Layout-Display.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Spacing/Spacing-Margin.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Spacing/Spacing-Padding.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TransitionsAndAnimations/TransitionsAndAnimations-Animation.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Typography/Typography-FontSize.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Typography/Typography-FontSmoothing.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Typography/Typography-FontWeight.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Typography/Typography-TextAlignment.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Typography/Typography-TextColor.md
Sources/Slipstream/TailwindCSS/Animation.swift
Sources/Slipstream/TailwindCSS/Condition.swift
Sources/Slipstream/TailwindCSS/TransitionsAndAnimations/View+animation.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/TransitionsAndAnimations/AnimationTests.swift

Add animation modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Backgrounds/Backgrounds-BackgroundImage.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Borders/Borders-Border.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/TailwindCSS/Backgrounds/View+backgroundImage.swift
Sources/Slipstream/TailwindCSS/Borders/View+border.swift
Sources/Slipstream/TailwindCSS/Size.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/Backgrounds/BackgroundImageTests.swift

Add backgroundImage modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Typography/Typography-FontDesign.md
Sources/Slipstream/TailwindCSS/Typography/View+fontDesign.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/Typography/FontDesignTests.swift

Add fontDesign modifier.

---

Sources/Slipstream/TailwindCSS/Condition.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift

Closes https://github.com/jverkoey/slipstream/issues/76

Add ability to combine Conditions together using the + operator.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FlexboxAndGrid/FlexboxAndGrid-JustifyContent.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/TailwindCSS/FlexboxAndGrid/View+justifyContent.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/FlexboxAndGrid/JustifyContentTests.swift

Add justifyContent modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/FlexboxAndGrid/FlexboxAndGrid-AlignItems.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/TailwindCSS/FlexboxAndGrid/View+alignItems.swift
Sources/Slipstream/TailwindCSS/FlexboxAndGrid/View+justifyContent.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/FlexboxAndGrid/AlignItemsTests.swift

Add alignItems modifier.

---

Sources/Slipstream/Documentation.docc/Views/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/Documentation.docc/Views/TailwindCSS/Typography/Typography-LineHeight.md
Sources/Slipstream/TailwindCSS/Typography/View+fontLeading.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/Typography/FontLeadingTests.swift

Add fontLeading modifier.

---

Package.resolved
Package.swift
Sources/Slipstream/Documentation.docc/Slipstream.md
Sources/Slipstream/Documentation.docc/Views/Fundamentals/Fundamentals.md
Sources/Slipstream/Documentation.docc/Views/W3C/Sections/Sections-Heading.md
Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md
Sources/Slipstream/Fundamentals/AnyView.swift
Sources/Slipstream/Fundamentals/View.swift
Sources/Slipstream/Markdown/MarkdownText.swift
Sources/Slipstream/W3C/Elements/GroupingContent/Paragraph.swift
Sources/Slipstream/W3C/Elements/Sections/Heading.swift
Tests/SlipstreamTests/Markdown/MarkdownTests.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/W3C/HeadingTests.swift
Tests/SlipstreamTests/W3C/ParagraphTests.swift

This view provides a generic way to render markdown content.

Add MarkdownText.

---

Sources/Slipstream/Documentation.docc/Views/W3C/EmbeddedContent/Image.md
Sources/Slipstream/Documentation.docc/Views/W3C/W3CAttributes.md
Sources/Slipstream/Documentation.docc/Views/W3C/W3CViews.md
Sources/Slipstream/Markdown/MarkdownText.swift
Sources/Slipstream/W3C/Attributes/View+accessibilityLabel.swift
Sources/Slipstream/W3C/Elements/EmbeddedContent/Image.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/W3C/ImageTests.swift

Add Image view.

---

Sources/Slipstream/Documentation.docc/TailwindCSS/Sizing/Sizing-Frame.md
Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Classes.md
Sources/Slipstream/TailwindCSS/Edge.swift
Sources/Slipstream/TailwindCSS/Sizing/FrameTypes/FrameHeightValue.swift
Sources/Slipstream/TailwindCSS/Sizing/FrameTypes/FrameMaxHeightValue.swift
Sources/Slipstream/TailwindCSS/Sizing/FrameTypes/FrameMaxWidthValue.swift
Sources/Slipstream/TailwindCSS/Sizing/FrameTypes/FrameMinHeightValue.swift
Sources/Slipstream/TailwindCSS/Sizing/FrameTypes/FrameMinWidthValue.swift
Sources/Slipstream/TailwindCSS/Sizing/FrameTypes/FrameWidthValue.swift
Sources/Slipstream/TailwindCSS/Sizing/View+frame.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/Sizing/FrameTests.swift
Tests/SlipstreamTests/TailwindCSS/Spacing/MarginTests.swift
Tests/SlipstreamTests/TailwindCSS/Spacing/PaddingTests.swift

Add frame modifier.

---

Sources/Slipstream/Documentation.docc/TailwindCSS/Backgrounds/Backgrounds-BackgroundColor.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Backgrounds/Backgrounds-BackgroundImage.md
Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/TailwindCSS/Backgrounds/View+background.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/Backgrounds/BackgroundColorTests.swift
Tests/SlipstreamTests/TailwindCSS/Backgrounds/BackgroundImageTests.swift

Add background color modifier.

---

Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Typography/Typography-TextDecoration.md
Sources/Slipstream/TailwindCSS/Color.swift
Sources/Slipstream/TailwindCSS/Typography/View+fontWeight.swift
Sources/Slipstream/TailwindCSS/Typography/View+textDecoration.swift
Tests/SlipstreamTests/TailwindCSS/Typography/TextDecorationTests.swift

Add textDecoration/underline/strikethrough modifiers.

---

Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Typography/Typography-FontStyle.md
Sources/Slipstream/TailwindCSS/Typography/View+fontStyle.swift
Tests/SlipstreamTests/TailwindCSS/Typography/FontStyleTests.swift

Add fontStyle modifier.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/GroupingContent/List.swift
Sources/Slipstream/W3C/Elements/GroupingContent/Listitem.swift
Tests/SlipstreamTests/W3C/ListTests.swift

Add List and ListItem views.

---

Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Typography/Typography-ListStyle.md
Sources/Slipstream/TailwindCSS/Typography/View+listStyle.swift
Tests/SlipstreamTests/TailwindCSS/Typography/ListStyleTests.swift

Add listStyle modifier.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/Markdown/MarkdownText.swift
Sources/Slipstream/W3C/Elements/Sections/Footer.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/W3C/FooterTests.swift

Add Footer element.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/Markdown/MarkdownText.swift
Sources/Slipstream/W3C/Elements/Sections/Navigation.swift
Tests/SlipstreamTests/W3C/NavigationTests.swift

Add Navigation element.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/TextLevelSemantics/Small.swift
Tests/SlipstreamTests/W3C/SmallTests.swift

Add Small element.

---

Sources/Slipstream/TailwindCSS/Layout/VStack.swift
Tests/SlipstreamTests/Sites/CatalogSiteTests.swift
Tests/SlipstreamTests/TailwindCSS/Layout/VStackTests.swift

This deviates from SwiftUI, but it's for my own sanity.

Default VStack to `start`-alignment.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/TextLevelSemantics/Strong.swift
Tests/SlipstreamTests/W3C/StrongTests.swift

Add Strong element.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/GroupingContent/Preformatted.swift
Tests/SlipstreamTests/W3C/PreformattedTests.swift

Add Preformatted element.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/TextLevelSemantics/Span.swift
Tests/SlipstreamTests/W3C/SpanTests.swift

Add Span element.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/TextLevelSemantics/Code.swift
Tests/SlipstreamTests/W3C/CodeTests.swift

Add Code element.

---

Sources/Slipstream/Documentation.docc/Slipstream.md
Sources/Slipstream/Documentation.docc/W3C/W3CAttributes.md
Sources/Slipstream/Fundamentals/AttributeModifier.swift
Sources/Slipstream/W3C/Attributes/View+data.swift
Tests/SlipstreamTests/Attributes/DataTests.swift

Closes https://github.com/jverkoey/slipstream/issues/134

Add data-* modifier.

---

Sources/Slipstream/Documentation.docc/Slipstream.md
Sources/Slipstream/Documentation.docc/W3C/W3CAttributes.md
Sources/Slipstream/W3C/Attributes/CrossOrigin.swift
Sources/Slipstream/W3C/Attributes/View+accessibilityLabel.swift
Sources/Slipstream/W3C/Elements/DocumentMetadata/Stylesheet.swift
Sources/Slipstream/W3C/Elements/EmbeddedContent/Image.swift
Sources/Slipstream/W3C/Elements/Scripting/Script.swift
Tests/SlipstreamTests/W3C/ImageTests.swift
Tests/SlipstreamTests/W3C/ScriptTests.swift
Tests/SlipstreamTests/W3C/StylesheetTests.swift

Closes https://github.com/jverkoey/slipstream/issues/136

Add support for the crossorigin attribute.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Layout/Layout-Position.md
Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/TailwindCSS/Layout/View+position.swift
Tests/SlipstreamTests/TailwindCSS/Layout/PositionTests.swift

Add position modifier.

---

Sources/Slipstream/Documentation.docc/TailwindCSS/Layout/Layout-Placement.md
Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/TailwindCSS/Layout/View+placement.swift
Sources/Slipstream/TailwindCSS/Sizing/View+frame.swift
Tests/SlipstreamTests/TailwindCSS/Layout/PlacementTests.swift

Add placement modifiers.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md
Sources/Slipstream/Documentation.docc/Guides/SlipstreamforSwiftUIDevelopers.md
Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Transforms/Transforms-Offset.md
Sources/Slipstream/TailwindCSS/Transforms/View+offset.swift
Tests/SlipstreamTests/TailwindCSS/Transforms/OffsetTests.swift

Add offset modifier.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Effects/Effects-Shadow.md
Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/TailwindCSS/Effects/View+shadow.swift
Tests/SlipstreamTests/TailwindCSS/Effects/ShadowTests.swift

Add shadow modifier.

---

Sources/Slipstream/Documentation.docc/TailwindCSS/Backgrounds/Backgrounds-BackgroundColor.md
Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/Forms/TextField.swift
Tests/SlipstreamTests/W3C/Forms/TextFieldTests.swift

Add TextField control.

---

Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/Forms/Button.swift
Sources/Slipstream/W3C/Elements/Forms/TextField.swift
Tests/SlipstreamTests/W3C/Forms/ButtonTests.swift

Add Button view.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Borders/Borders-Outline.md
Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/TailwindCSS/Borders/View+border.swift
Sources/Slipstream/TailwindCSS/Borders/View+outline.swift
Tests/SlipstreamTests/TailwindCSS/Borders/OutlineTests.swift

Add outline modifier.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md
Sources/Slipstream/Documentation.docc/TailwindCSS/Borders/Borders-Ring.md
Sources/Slipstream/Documentation.docc/TailwindCSS/TailwindCSS-Utilities.md
Sources/Slipstream/TailwindCSS/Borders/View+ring.swift
Tests/SlipstreamTests/TailwindCSS/Borders/RingTests.swift

Add ring modifier.

---

Sources/Slipstream/Documentation.docc/W3C/Forms/Forms-Form.md
Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/Forms/Form.swift
Tests/SlipstreamTests/W3C/Forms/FormTests.swift

[feature] Add Form element.

---

Tests/SlipstreamTests/Markdown/MarkdownTests.swift

Forgot to add the environment overrides.

Fix markdown tests.

---

.github/workflows/package-test.yml
.github/workflows/static.yml
Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md
Sources/Slipstream/Documentation.docc/W3C/EmbeddedContent/Source.md
Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/EmbeddedContent/Image.swift
Sources/Slipstream/W3C/Elements/EmbeddedContent/Picture.swift
Sources/Slipstream/W3C/Elements/EmbeddedContent/Source.swift
Tests/SlipstreamTests/W3C/PictureTests.swift
Tests/SlipstreamTests/W3C/SourceTests.swift

Part of https://github.com/jverkoey/slipstream/issues/25

Add Picture and Source.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md
Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/EmbeddedContent/IFrame.swift
Tests/SlipstreamTests/W3C/IFrameTests.swift

Add iframe view.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md
Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/Forms/Option.swift
Sources/Slipstream/W3C/Elements/Forms/Picker.swift
Tests/SlipstreamTests/W3C/Forms/OptionTests.swift
Tests/SlipstreamTests/W3C/Forms/PickerTests.swift

Add Picker and Option.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md
Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/DocumentMetadata/Preconnect.swift
Tests/SlipstreamTests/W3C/PreconnectTests.swift

Add Preconnect.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md
Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/DocumentMetadata/Canonical.swift
Tests/SlipstreamTests/W3C/CanonicalTests.swift

Add Canonical.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md
Sources/Slipstream/Documentation.docc/W3C/W3CViews.md
Sources/Slipstream/W3C/Elements/GroupingContent/DocumentMain.swift
Tests/SlipstreamTests/W3C/DocumentMainTests.swift

Add DocumentMain.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md
Sources/Slipstream/TailwindCSS/Transition.swift
Sources/Slipstream/TailwindCSS/TransitionsAndAnimations/View+transition.swift
Tests/SlipstreamTests/TailwindCSS/TransitionsAndAnimations/TransitionTests.swift

Add transition modifier.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md
Sources/Slipstream/Documentation.docc/TailwindCSS/FlexboxAndGrid/FlexboxAndGrid-GridColumnStartEnd.md
Sources/Slipstream/TailwindCSS/FlexboxAndGrid/View+gridCellColumns.swift
Sources/Slipstream/TailwindCSS/GridSpan.swift
Tests/SlipstreamTests/TailwindCSS/FlexboxAndGrid/GridCellColumnsTests.swift

Add gridCellColumns modifier.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForTailwindCSSDevelopers.md
Sources/Slipstream/Documentation.docc/TailwindCSS/FlexboxAndGrid/FlexboxAndGrid-GridRowStartEnd.md
Sources/Slipstream/TailwindCSS/FlexboxAndGrid/View+gridCellRows.swift
Tests/SlipstreamTests/TailwindCSS/FlexboxAndGrid/GridCellRowsTests.swift

Add gridCellRows modifier.

---

Sources/Slipstream/Documentation.docc/Guides/SlipstreamForWebDevelopers.md
Sources/Slipstream/W3C/Elements/DocumentMetadata/Redirect.swift
Tests/SlipstreamTests/W3C/RedirectTests.swift

Add Redirect.
